// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Web3 from "./libraries/Web3.js";

var longshortContractAbi = Web3.makeAbi([""]);

export {
  longshortContractAbi ,
  
}
/* longshortContractAbi Not a pure module */
