// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Login from "./components/Login/Login.js";
import * as React from "react";
import * as Queries from "./libraries/Queries.js";
import * as MiniLoader from "./components/UI/MiniLoader.js";
import * as FormatMoney from "./components/UI/FormatMoney.js";
import * as MarketsList from "./components/Markets/MarketsList.js";
import * as Router from "next/router";
import * as StakeDetails from "./StakeDetails.js";
import * as AccessControl from "./components/AccessControl.js";

function Dashboard(Props) {
  var router = Router.useRouter();
  var systemStateQuery = Curry.app(Queries.LatestSystemState.use, [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined
      ]);
  var match = systemStateQuery.data;
  var tmp;
  if (systemStateQuery.loading) {
    tmp = React.createElement(MiniLoader.make, {});
  } else if (systemStateQuery.error !== undefined) {
    tmp = "Error loading data";
  } else if (match !== undefined) {
    var match$1 = match.systemStates;
    if (match$1.length !== 1) {
      tmp = "Query returned wrong number of results";
    } else {
      var match$2 = match$1[0];
      tmp = React.createElement("div", {
            className: "col-span-2"
          }, React.createElement("div", {
                className: "p-5 flex flex-col items-center justify-center bg-white bg-opacity-75 rounded"
              }, React.createElement("h2", {
                    className: "text-lg"
                  }, "Total value locked"), React.createElement("p", {
                    className: "text-primary text-4xl"
                  }, "BUSD " + FormatMoney.formatEther(match$2.totalValueLocked))));
    }
  } else {
    tmp = "Error getting data";
  }
  return React.createElement(AccessControl.make, {
              children: React.createElement("div", {
                    className: "grid grid-cols-2 gap-4 items-center my-5"
                  }, React.createElement(React.Fragment, undefined, tmp), React.createElement("div", undefined, React.createElement(MarketsList.make, {})), React.createElement("div", undefined, React.createElement(StakeDetails.make, {}))),
              alternateComponent: React.createElement("h1", {
                    onClick: (function (param) {
                        router.push("/login?nextPath=/dashboard");
                        
                      })
                  }, React.createElement(Login.make, {}))
            });
}

var make = Dashboard;

var $$default = Dashboard;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* Login Not a pure module */
