// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as DashboardLi from "./DashboardLi.js";

function DashboardUl(Props) {
  var list = Props.list;
  var link = Props.link;
  var content = React.createElement("ul", {
        className: "p-6 py-4 pl-10"
      }, Belt_Array.mapWithIndex(list, (function (index, param) {
              var prefix = param.prefix;
              return React.createElement(DashboardLi.make, {
                          prefix: prefix,
                          value: param.value,
                          first: index === 0,
                          suffix: param.suffix,
                          key: prefix + String(index)
                        });
            })));
  return Belt_Option.mapWithDefault(link, content, (function (linkStr) {
                return React.createElement("a", {
                            href: linkStr,
                            target: "_blank"
                          }, content);
              }));
}

var make = DashboardUl;

export {
  make ,
  
}
/* react Not a pure module */
