// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Config = require("../Config.js");

function ComingSoon(Props) {
  return React.createElement("div", {
              className: "bg-primary text-center text-sm text-white p-1 mb-2 "
            }, "🏗 The protocol is under active development, join our ", React.createElement("a", {
                  className: "hover:bg-white hover:text-primary py-1 ",
                  href: Config.discordInviteLink,
                  rel: "noopener noreferrer",
                  target: "_blank"
                }, "discord"), " to get the latest updates  🏗");
}

var make = ComingSoon;

exports.make = make;
/* react Not a pure module */
