// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function EcosystemPartners(Props) {
  return React.createElement("section", {
              className: "absolute bottom-0 py-2 w-screen flex flex-col items-center justify-center"
            }, React.createElement("div", {
                  className: "w-full mx-auto max-w-6xl flex flex-col md:flex-row items-center justify-center"
                }, React.createElement("img", {
                      className: "h-12 mx-2",
                      src: "/img/partners/polygon.png"
                    }), React.createElement("img", {
                      className: "h-12 mx-2",
                      src: "/img/partners/aave.png"
                    }), React.createElement("img", {
                      className: "h-12 mx-2",
                      src: "/img/partners/chainlink.png"
                    }), React.createElement("img", {
                      className: "h-12 mx-2",
                      src: "/img/partners/thegraph.png"
                    }), React.createElement("img", {
                      className: "h-12 mx-2",
                      src: "/img/partners/poap.svg"
                    })));
}

var make = EcosystemPartners;

exports.make = make;
/* react Not a pure module */
