// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Button = require("../components/UI/Base/Button.js");
var Heading = require("./components/Heading.js");
var Router = require("next/router");

function Governance(Props) {
  var router = Router.useRouter();
  return React.createElement("section", {
              className: "py-10 min-h-screen w-screen flex flex-col items-center justify-center ballot-box",
              id: "governance"
            }, React.createElement("div", {
                  className: "max-w-5xl flex flex-col md:flex-row justify-evenly items-center mx-auto"
                }, React.createElement("div", {
                      className: "w-full md:w-1/2 order-2 md:order-1 p-4 md:p-0"
                    }, React.createElement(Heading.make, {
                          title: "governance",
                          suffixEmoji: "👤"
                        }), React.createElement("p", {
                          className: "text-lg md:text-2xl p-4 md:p-0 bg-white bg-opacity-80 rounded-lg md:bg-transparent"
                        }, "The FLT token governs the float capital protocol. The right governance model will direct and shape the protocol through community lead proposals in a decentralised and fair manor. The future of Float Capital will be dictated by its users."), React.createElement("div", {
                          className: "flex flex-row my-4 items-center justify-evenly md:justify-start  "
                        }, React.createElement("div", {
                              className: "mr-4"
                            }, React.createElement("a", {
                                  href: "https://docs.float.capital/docs/governance",
                                  rel: "noopener noreferrer",
                                  target: "_blank"
                                }, React.createElement(Button.make, {
                                      children: "Read more"
                                    }))), React.createElement("div", undefined, React.createElement(Button.make, {
                                  onClick: (function (param) {
                                      router.push("/app/stake-markets");
                                      
                                    }),
                                  children: "Earn FLT"
                                })))), React.createElement("div", {
                      className: "w-full md:w-1/2 order-1 md:order-2"
                    })));
}

var make = Governance;

exports.make = make;
/* react Not a pure module */
