// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Tick = require("../UI/Base/Tick.js");
var Modal = require("../UI/Base/Modal.js");
var React = require("react");
var Loader = require("../UI/Base/Loader.js");
var MessageUsOnDiscord = require("../Ethereum/MessageUsOnDiscord.js");
var ViewOnBlockExplorer = require("../Ethereum/ViewOnBlockExplorer.js");

function WithdrawTxStatusModal(Props) {
  var txState = Props.txState;
  if (typeof txState === "number") {
    if (txState === /* UnInitialised */0) {
      return null;
    } else {
      return React.createElement(Modal.make, {
                  id: 11,
                  children: React.createElement("div", {
                        className: "text-center m-3"
                      }, React.createElement(Loader.Ellipses.make, {}), React.createElement("h1", undefined, "Confirm the transaction to withdraw your DAI"))
                });
    }
  }
  switch (txState.TAG | 0) {
    case /* SignedAndSubmitted */0 :
        return React.createElement(Modal.make, {
                    id: 12,
                    children: React.createElement("div", {
                          className: "text-center m-3"
                        }, React.createElement("div", {
                              className: "m-2"
                            }, React.createElement(Loader.Mini.make, {})), React.createElement("p", undefined, "Withdraw transaction pending... "), React.createElement(ViewOnBlockExplorer.make, {
                              txHash: txState._0
                            }))
                  });
    case /* Declined */1 :
        return React.createElement(Modal.make, {
                    id: 14,
                    children: React.createElement("div", {
                          className: "text-center m-3"
                        }, React.createElement("p", undefined, "The transaction was rejected by your wallet"), React.createElement(MessageUsOnDiscord.make, {}))
                  });
    case /* Complete */2 :
        return React.createElement(Modal.make, {
                    id: 13,
                    children: React.createElement("div", {
                          className: "text-center m-3"
                        }, React.createElement(Tick.make, {}), React.createElement("p", undefined, "Transaction complete 🎉"), React.createElement(ViewOnBlockExplorer.make, {
                              txHash: txState._0.transactionHash
                            }))
                  });
    case /* Failed */3 :
        return React.createElement(Modal.make, {
                    id: 15,
                    children: React.createElement("div", {
                          className: "text-center m-3"
                        }, React.createElement("h1", undefined, "The transaction failed."), React.createElement(ViewOnBlockExplorer.make, {
                              txHash: txState._0
                            }), React.createElement(MessageUsOnDiscord.make, {}))
                  });
    
  }
}

var make = WithdrawTxStatusModal;

exports.make = make;
/* Tick Not a pure module */
