// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Queries = require("../Queries.bs.js");
var JsPromise = require("../libraries/Js.Promise/JsPromise.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Converters = require("../stateChanges/Converters.bs.js");
var StateChange = require("../stateChanges/StateChange.bs.js");
var TestFramework = require("reason-test-framework/src/TestFramework.bs.js");

function emptyPromise(param) {
  return new Promise((function (resolve, param) {
                return resolve(Converters.emptyEventGroups);
              }));
}

var allStateChanges = {
  contents: new Promise((function (resolve, param) {
          return resolve(Converters.emptyEventGroups);
        }))
};

Curry._2(TestFramework.describe, "All Tests", (function (param) {
        Curry._1(param.beforeAll, (function (param) {
                var allStateChangesRaw = Queries.getAllStateChanges(undefined);
                allStateChanges.contents = JsPromise.$$catch(StateChange.splitIntoEventGroups(StateChange.getAllStateChangeEvents(allStateChangesRaw)), (function (error) {
                        console.log({
                              "critical error fetching events": error
                            });
                        
                      }));
                console.log("Saving the promise", allStateChanges.contents);
                
              }));
        Curry._2(TestFramework.describe, "V1 event", (function (param) {
                var testAsync = param.testAsync;
                Curry._2(testAsync, "should occur exactly ONCE", (function (param) {
                        var expectEqual = param.expectEqual;
                        var callback = param.callback;
                        allStateChanges.contents.then(function (param) {
                              Curry._2(expectEqual, param.allLongShortV1Events.length, 1);
                              return Curry._1(callback, undefined);
                            });
                        
                      }));
                return Curry._2(testAsync, "should setup the correct initial data in the global state", (function (param) {
                              var expectNotEqual = param.expectNotEqual;
                              var expectEqual = param.expectEqual;
                              var expectTrue = param.expectTrue;
                              var callback = param.callback;
                              allStateChanges.contents.then(function (param) {
                                    var match = Belt_Array.getExn(param.allLongShortV1Events, 0);
                                    var match$1 = match.data;
                                    var staker = match$1.staker;
                                    var tokenFactory = match$1.tokenFactory;
                                    var admin = match$1.admin;
                                    var timestamp = match.timestamp;
                                    Queries.getGlobalStateAtBlock(match.blockNumber).then(function (result) {
                                          if (result !== undefined) {
                                            Curry._2(expectEqual, result.contractVersion.toString(), "1");
                                            Curry._2(expectEqual, result.latestMarketIndex.toString(), "0");
                                            Curry._2(expectEqual, result.totalFloatMinted.toString(), "0");
                                            Curry._2(expectEqual, result.totalUsers.toString(), "1");
                                            Curry._2(expectEqual, result.timestampLaunched.toString(), String(timestamp));
                                            Curry._2(expectEqual, result.staker.address, staker);
                                            Curry._2(expectEqual, result.tokenFactory.address, tokenFactory);
                                            Curry._2(expectEqual, result.adminAddress, admin);
                                            Curry._2(expectNotEqual, result.txHash, "");
                                          } else {
                                            Curry._1(expectTrue, false);
                                          }
                                          return Curry._1(callback, undefined);
                                        });
                                    
                                  });
                              
                            }));
              }));
        Curry._2(TestFramework.describe, "SyntheticMarketCreated event", (function (param) {
                var testAsync = param.testAsync;
                Curry._2(testAsync, "should occur more than ONCE (must test!)", (function (param) {
                        var expectTrue = param.expectTrue;
                        var callback = param.callback;
                        allStateChanges.contents.then(function (param) {
                              Curry._1(expectTrue, param.allSyntheticMarketCreatedEvents.length >= 1);
                              return Curry._1(callback, undefined);
                            });
                        
                      }));
                Curry._2(testAsync, "synthetic market shouldn't exist before this event is emitted", (function (param) {
                        var expectTrue = param.expectTrue;
                        var callback = param.callback;
                        allStateChanges.contents.then(function (param) {
                                return Promise.all(Belt_Array.map(param.allSyntheticMarketCreatedEvents, (function (param) {
                                                  return Queries.getSyntheticMarketAtBlock(param.data.marketIndex.toString(), param.blockNumber - 1 | 0).then(function (result) {
                                                              if (result !== undefined) {
                                                                return Curry._1(expectTrue, false);
                                                              } else {
                                                                return Curry._1(expectTrue, true);
                                                              }
                                                            });
                                                })));
                              }).then(function (param) {
                              return Curry._1(callback, undefined);
                            });
                        
                      }));
                Curry._2(testAsync, "should create a SyntheticMarket with correct ID and initial data", (function (param) {
                        var expectEqual = param.expectEqual;
                        var expectTrue = param.expectTrue;
                        var callback = param.callback;
                        allStateChanges.contents.then(function (param) {
                                return Promise.all(Belt_Array.map(param.allSyntheticMarketCreatedEvents, (function (param) {
                                                  var match = param.data;
                                                  var oracleAddress = match.oracleAddress;
                                                  var symbol = match.symbol;
                                                  var name = match.name;
                                                  var paymentAddress = match.paymentAddress;
                                                  var shortTokenAddress = match.shortTokenAddress;
                                                  var longTokenAddress = match.longTokenAddress;
                                                  var marketIndex = match.marketIndex;
                                                  var txHash = param.txHash;
                                                  var timestamp = param.timestamp;
                                                  var blockNumber = param.blockNumber;
                                                  console.log({
                                                        "market index": marketIndex.toString(),
                                                        txHash: txHash
                                                      });
                                                  return Queries.getSyntheticMarketAtBlock(marketIndex.toString(), blockNumber).then(function (result) {
                                                              if (result === undefined) {
                                                                return Curry._1(expectTrue, false);
                                                              }
                                                              var marketIndex = result.marketIndex;
                                                              var paymentTokenId = result.paymentToken.id;
                                                              Curry._2(expectEqual, result.id, marketIndex.toString());
                                                              Curry._2(expectEqual, String(timestamp), result.timestampCreated.toString());
                                                              Curry._2(expectEqual, txHash, result.txHash);
                                                              Curry._2(expectEqual, String(blockNumber), result.blockNumberCreated.toString());
                                                              Curry._2(expectEqual, name, result.name);
                                                              Curry._2(expectEqual, symbol, result.symbol);
                                                              Curry._2(expectEqual, oracleAddress, result.oracleAddress);
                                                              Curry._2(expectEqual, result.kPeriod.toString(), "0");
                                                              Curry._2(expectEqual, result.kMultiplier.toString(), "0");
                                                              Curry._2(expectEqual, result.previousOracleAddresses, []);
                                                              Curry._2(expectEqual, result.syntheticLong.id, longTokenAddress);
                                                              Curry._2(expectEqual, result.syntheticShort.id, shortTokenAddress);
                                                              Curry._2(expectEqual, result.latestSystemState.id, marketIndex.toString() + "-0");
                                                              console.log({
                                                                    paymentTokenId: paymentTokenId,
                                                                    paymentAddress: paymentAddress
                                                                  });
                                                              return Curry._2(expectEqual, paymentTokenId, paymentAddress);
                                                            });
                                                })));
                              }).then(function (param) {
                              return Curry._1(callback, undefined);
                            });
                        
                      }));
                var testSyntheticToken = function (syntheticTokenQuery, tokenAddress, timestamp, marketIndex, isLong, expectEqual) {
                  var priceHistory = syntheticTokenQuery.priceHistory;
                  var match = syntheticTokenQuery.latestPrice;
                  var tokenStrTypeUpper = isLong ? "Long" : "Short";
                  var tokenStrTypeLower = isLong ? "long" : "short";
                  Curry._2(expectEqual, tokenAddress, syntheticTokenQuery.tokenAddress);
                  Curry._2(expectEqual, syntheticTokenQuery.syntheticMarket.id, marketIndex.toString());
                  Curry._2(expectEqual, syntheticTokenQuery.tokenType, tokenStrTypeUpper);
                  Curry._2(expectEqual, syntheticTokenQuery.floatMintedFromSpecificToken.toString(), "0");
                  Curry._2(expectEqual, match.id, "latestPrice-" + marketIndex.toString() + "-" + tokenStrTypeLower);
                  Curry._2(expectEqual, match.price.id, marketIndex.toString() + "-" + tokenStrTypeLower + "-" + String(timestamp));
                  var initialPriceId = priceHistory[0].id;
                  Curry._2(expectEqual, initialPriceId, marketIndex.toString() + "-" + tokenStrTypeLower + "-" + String(timestamp));
                  Curry._2(expectEqual, syntheticTokenQuery.tokenSupply.toString(), "0");
                  Curry._2(expectEqual, syntheticTokenQuery.id, tokenAddress);
                  return Curry._2(expectEqual, String(priceHistory.length), "1");
                };
                return Curry._2(testAsync, "should create SyntheticTokens with correct IDs and initial data", (function (param) {
                              var expectEqual = param.expectEqual;
                              var expectTrue = param.expectTrue;
                              var callback = param.callback;
                              allStateChanges.contents.then(function (param) {
                                      return Promise.all(Belt_Array.map(param.allSyntheticMarketCreatedEvents, (function (param) {
                                                        var match = param.data;
                                                        var shortTokenAddress = match.shortTokenAddress;
                                                        var longTokenAddress = match.longTokenAddress;
                                                        var marketIndex = match.marketIndex;
                                                        var timestamp = param.timestamp;
                                                        var blockNumber = param.blockNumber;
                                                        return Promise.all([
                                                                    Queries.getSyntheticTokenAtBlock(longTokenAddress, blockNumber).then(function (result) {
                                                                          if (result !== undefined) {
                                                                            return testSyntheticToken(result, longTokenAddress, timestamp, marketIndex, true, expectEqual);
                                                                          } else {
                                                                            return Curry._1(expectTrue, false);
                                                                          }
                                                                        }),
                                                                    Queries.getSyntheticTokenAtBlock(shortTokenAddress, blockNumber).then(function (result) {
                                                                          if (result !== undefined) {
                                                                            return testSyntheticToken(result, shortTokenAddress, timestamp, marketIndex, false, expectEqual);
                                                                          } else {
                                                                            return Curry._1(expectTrue, false);
                                                                          }
                                                                        })
                                                                  ]);
                                                      })));
                                    }).then(function (param) {
                                    return Curry._1(callback, undefined);
                                  });
                              
                            }));
              }));
        return Curry._2(param.testAsync, "All events should be classified - NO UNKNOWN EVENTS", (function (param) {
                      var expectEqual = param.expectEqual;
                      var callback = param.callback;
                      allStateChanges.contents.then(function (param) {
                            Curry._2(expectEqual, param.allUnclassifiedEvents.length, 0);
                            return Curry._1(callback, undefined);
                          });
                      
                    }));
      }));

exports.emptyPromise = emptyPromise;
exports.allStateChanges = allStateChanges;
/* allStateChanges Not a pure module */
