// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mint from "../../Mint.js";
import * as React from "react";
import * as LineGraph from "../LineGraph.js";
import * as MarketCard from "./MarketCard.js";

function Market(Props) {
  var marketData = Props.marketData;
  return React.createElement("div", undefined, React.createElement(MarketCard.make, {
                  marketData: marketData
                }), React.createElement(LineGraph.make, {}), React.createElement(Mint.Mint.make, {}), React.createElement("p", undefined, "stake position form"));
}

var make = Market;

export {
  make ,
  
}
/* Mint Not a pure module */
