// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Config from "../../Config.js";
import * as Ethers from "../../ethereum/Ethers.js";
import * as Contracts from "../../ethereum/Contracts.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as RootProvider from "../../libraries/RootProvider.js";
import * as ContractActions from "../../ethereum/ContractActions.js";

function useDaiBalance(param) {
  var optChainId = RootProvider.useNetworkId(undefined);
  var optUserId = RootProvider.useCurrentUser(undefined);
  var optProviderOrSigner = ContractActions.useProviderOrSigner(undefined);
  var match = React.useState(function () {
        
      });
  var setDaiBalance = match[1];
  React.useEffect((function () {
          if (optChainId !== undefined && optProviderOrSigner !== undefined && optUserId !== undefined) {
            Contracts.Erc20.make(Config.daiContractAddress(String(optChainId)), optProviderOrSigner).balanceOf(Caml_option.valFromOption(optUserId)).then(function (balance) {
                  return Curry._1(setDaiBalance, (function (param) {
                                return Caml_option.some(balance);
                              }));
                });
          }
          
        }), [
        optChainId,
        optUserId
      ]);
  return match[0];
}

function DaiBalance(Props) {
  var optBalance = useDaiBalance(undefined);
  return React.createElement(React.Fragment, undefined, optBalance !== undefined ? React.createElement("h1", undefined, "dai balance: " + Ethers.Utils.formatEther(Caml_option.valFromOption(optBalance)) + " DAI") : React.createElement("h1", undefined, "Loading dai balance"));
}

var make = DaiBalance;

export {
  useDaiBalance ,
  make ,
  
}
/* react Not a pure module */
