// Generated by ReScript, PLEASE EDIT WITH CARE

import Swr from "swr";
import * as Misc from "../../libraries/Misc.js";
import * as React from "react";
import * as Config from "../../Config.js";
import * as Ethers from "../../ethereum/Ethers.js";
import * as Contracts from "../../ethereum/Contracts.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as RootProvider from "../../libraries/RootProvider.js";
import * as ContractActions from "../../ethereum/ContractActions.js";
import * as SwrSyncStorage from "swr-sync-storage";

Misc.onlyExecuteClientSide(function (prim) {
      SwrSyncStorage.syncWithSessionStorage();
      
    });

function useDaiBalance(param) {
  var optChainId = RootProvider.useNetworkId(undefined);
  var optUserId = RootProvider.useCurrentUser(undefined);
  var optProviderOrSigner = ContractActions.useProviderOrSigner(undefined);
  var fetchBalanceFunction = function (param, chainId, userId) {
    var providerOrSigner = Belt_Option.getExn(optProviderOrSigner);
    return Contracts.Erc20.make(Config.daiContractAddress(String(chainId)), providerOrSigner).balanceOf(userId);
  };
  return Swr((function (param) {
                if (optChainId !== undefined && optProviderOrSigner !== undefined && optUserId !== undefined) {
                  return [
                          "chainBalance",
                          optChainId,
                          Caml_option.valFromOption(optUserId)
                        ];
                }
                
              }), fetchBalanceFunction, undefined);
}

function DaiBalance(Props) {
  var match = useDaiBalance(undefined);
  var optBalance = match.data;
  return React.createElement(React.Fragment, undefined, optBalance !== undefined ? React.createElement("h1", undefined, "dai balance: " + Ethers.Utils.formatEther(Caml_option.valFromOption(optBalance)) + " DAI") : React.createElement("h1", undefined, "Loading dai balance"));
}

var make = DaiBalance;

export {
  useDaiBalance ,
  make ,
  
}
/*  Not a pure module */
