// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MiniLoader from "../UI/MiniLoader.js";
import * as ContractHooks from "../Testing/Admin/ContractHooks.js";

function DaiBalance(Props) {
  var match = ContractHooks.useDaiBalanceRefresh(undefined);
  return React.createElement(React.Fragment, undefined, match.data !== undefined ? React.createElement("div", {
                    className: "flex justify-between w-full"
                  }, React.createElement("p", undefined, "BUSD balance: "), React.createElement("p", undefined, "$${FormatMoney.formatEther(balance)}")) : React.createElement(MiniLoader.make, {}));
}

var make = DaiBalance;

export {
  make ,
  
}
/* react Not a pure module */
