// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var marketsInfoData = (require('./market-data.json'));

function getMarketInfoUnsafe(index) {
  return Belt_Option.getWithDefault(Belt_Array.get(marketsInfoData, index - 1 | 0), {
              name: "",
              description: "",
              oracleHeartbeat: 300,
              icon: "/icons/tokens/placeholder.svg",
              oracleDecimals: 8
            });
}

exports.marketsInfoData = marketsInfoData;
exports.getMarketInfoUnsafe = getMarketInfoUnsafe;
/* marketsInfoData Not a pure module */
