// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CONSTANTS = require("../CONSTANTS.js");

var config = (require('config_file'));

var isPolygon = config.networkId === CONSTANTS.polygon.chainId;

var match = config.contracts;

var graphEndpoint = config.graphEndpoint;

var priceHistoryGraphEndpoint = config.priceHistoryGraphEndpoint;

var aaveGraphEndpoint = config.aaveGraphEndpoint;

var networkId = config.networkId;

var networkName = config.networkName;

var torusName = config.torusName;

var networkCurrencyName = config.networkCurrencyName;

var networkCurrencySymbol = config.networkCurrencySymbol;

var rpcEndopint = config.rpcEndopint;

var paymentTokenName = config.paymentTokenName;

var blockExplorer = config.blockExplorer;

var blockExplorerName = config.blockExplorerName;

var discordInviteLink = config.discordInviteLink;

var polygonBridgeLink = config.polygonBridgeLink;

var web3PollingInterval = config.web3PollingInterval;

var apolloConnectToDevTools = config.apolloConnectToDevTools;

var longShort = match.LongShort;

var staker = match.Staker;

var dai = match.Dai;

var floatToken = match.FloatToken;

exports.config = config;
exports.isPolygon = isPolygon;
exports.graphEndpoint = graphEndpoint;
exports.priceHistoryGraphEndpoint = priceHistoryGraphEndpoint;
exports.aaveGraphEndpoint = aaveGraphEndpoint;
exports.networkId = networkId;
exports.networkName = networkName;
exports.torusName = torusName;
exports.networkCurrencyName = networkCurrencyName;
exports.networkCurrencySymbol = networkCurrencySymbol;
exports.rpcEndopint = rpcEndopint;
exports.paymentTokenName = paymentTokenName;
exports.blockExplorer = blockExplorer;
exports.blockExplorerName = blockExplorerName;
exports.discordInviteLink = discordInviteLink;
exports.polygonBridgeLink = polygonBridgeLink;
exports.web3PollingInterval = web3PollingInterval;
exports.apolloConnectToDevTools = apolloConnectToDevTools;
exports.longShort = longShort;
exports.staker = staker;
exports.dai = dai;
exports.floatToken = floatToken;
/* config Not a pure module */
