// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Misc from "../../libraries/Misc.js";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function AddBinanceToMetamask(Props) {
  var ethObj = window.ethereum;
  if (ethObj === undefined) {
    return null;
  }
  var ethObj$1 = Caml_option.valFromOption(ethObj);
  return React.createElement("div", {
              className: "flex justify-start align-center",
              onClick: (function (_event) {
                  return Misc.onlyExecuteClientSide(function (param) {
                              ethObj$1.request({
                                    method: "wallet_addEthereumChain",
                                    params: [{
                                        chainId: "0x61",
                                        chainName: "BSC testnet",
                                        nativeCurrency: {
                                          name: "Test BNB",
                                          symbol: "BNB",
                                          decimals: 18
                                        },
                                        rpcUrls: [
                                          "https://data-seed-prebsc-1-s2.binance.org:8545/",
                                          "https://data-seed-prebsc-2-s2.binance.org:8545/",
                                          "https://data-seed-prebsc-1-s3.binance.org:8545/",
                                          "https://data-seed-prebsc-2-s3.binance.org:8545/"
                                        ],
                                        blockExplorerUrls: ["https://testnet.bscscan.com/"]
                                      }]
                                  });
                              
                            });
                })
            }, React.createElement("div", {
                  className: "text-sm"
                }, "Go to the BSC Test Network "), React.createElement("img", {
                  className: "h-5 ml-1",
                  src: "/icons/metamask.svg"
                }));
}

var make = AddBinanceToMetamask;

export {
  make ,
  
}
/* Misc Not a pure module */
