// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Misc from "../../libraries/Misc.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function requestStructure(tokenAddress, tokenSymbol) {
  return {
          method: "wallet_watchAsset",
          params: {
            type: "ERC20",
            options: {
              address: tokenAddress,
              symbol: tokenSymbol.slice(0, 5),
              decimals: "18",
              image: undefined
            }
          }
        };
}

function AddToMetamask(Props) {
  var tokenAddress = Props.tokenAddress;
  var tokenSymbol = Props.tokenSymbol;
  var callbackOpt = Props.callback;
  var childrenOpt = Props.children;
  var callback = callbackOpt !== undefined ? callbackOpt : (function (param) {
        
      });
  var children = childrenOpt !== undefined ? Caml_option.valFromOption(childrenOpt) : React.createElement("img", {
          className: "h-5 ml-1",
          src: "/icons/metamask.svg"
        });
  var ethObj = window.ethereum;
  if (ethObj === undefined) {
    return null;
  }
  var ethObj$1 = Caml_option.valFromOption(ethObj);
  return React.createElement("div", {
              className: "flex justify-start align-center",
              onClick: (function (_event) {
                  return Misc.onlyExecuteClientSide(function (param) {
                              ethObj$1.request(requestStructure(tokenAddress, tokenSymbol));
                              return Curry._1(callback, undefined);
                            });
                })
            }, children);
}

var make = AddToMetamask;

export {
  requestStructure ,
  make ,
  
}
/* Misc Not a pure module */
