// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ethers from "../../ethereum/Ethers.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function toCentsFixedNoRounding(floatString) {
  return Belt_Option.getWithDefault(Caml_option.null_to_opt(floatString.match(/^\d+[.]\d\d/g)), ["0.00"])[0];
}

function format(__x) {
  return __x.replace(/\d(?=(\d{3})+\.)/g, "$&,");
}

function formatFloat(number) {
  return format(number.toFixed(2));
}

function formatEther(rawNumber) {
  return format(Ethers.Utils.formatEther(rawNumber));
}

function formatEtherRound(rawNumber) {
  var number = Number(Ethers.Utils.formatEther(rawNumber));
  return format(number.toFixed(2));
}

export {
  toCentsFixedNoRounding ,
  format ,
  formatFloat ,
  formatEther ,
  formatEtherRound ,
  
}
/* Ethers Not a pure module */
