// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ethers from "../../ethereum/Ethers.js";

function format(__x) {
  return __x.replace(/\d(?=(\d{3})+\.)/g, "$&,");
}

function formatInt(__x) {
  return __x.replace(/\d(?=(\d{3})+$)/g, "$&,");
}

function formatFloat(digitsOpt, number) {
  var digits = digitsOpt !== undefined ? digitsOpt : 2;
  return format(number.toFixed(digits));
}

function toCentsFixedNoRounding(digitsOpt, floatString) {
  var digits = digitsOpt !== undefined ? digitsOpt : 2;
  return formatFloat(digits, Number(floatString));
}

function formatEther(digitsOpt, rawNumber) {
  var digits = digitsOpt !== undefined ? digitsOpt : 2;
  return toCentsFixedNoRounding(digits, Ethers.Utils.formatEther(rawNumber));
}

export {
  format ,
  formatInt ,
  formatFloat ,
  toCentsFixedNoRounding ,
  formatEther ,
  
}
/* Ethers Not a pure module */
