// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function MiniLoader(Props) {
  return React.createElement("img", {
              className: "w-6 mx-auto",
              src: "/img/mini-loading.gif"
            });
}

var make = MiniLoader;

exports.make = make;
/* react Not a pure module */
