// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function StartTrading(Props) {
  return React.createElement("div", {
              className: "floating w-full"
            }, React.createElement(Link, {
                  href: "/markets",
                  children: React.createElement("span", {
                        className: "cursor-pointer hover:opacity-70 w-full flex justify-center"
                      }, React.createElement("img", {
                            className: "p-4",
                            src: "/img/start-trading.png"
                          }))
                }));
}

var Link$1;

var make = StartTrading;

export {
  Link$1 as Link,
  make ,
  
}
/* react Not a pure module */
