// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Form from "../Testing/Admin/Form.js";
import * as Next from "../../bindings/Next.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Button from "../UI/Button.js";
import * as Config from "../../Config.js";
import * as Ethers from "../../ethereum/Ethers.js";
import * as Loader from "../UI/Loader.js";
import * as Ethers$1 from "ethers";
import * as ViewBox from "../UI/ViewBox.js";
import * as Contracts from "../../ethereum/Contracts.js";
import * as Formality from "re-formality/src/Formality.js";
import * as AmountInput from "../UI/AmountInput.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Router from "next/router";
import * as ContractHooks from "../Testing/Admin/ContractHooks.js";
import * as ContractActions from "../../ethereum/ContractActions.js";
import * as Formality__ReactUpdate from "re-formality/src/Formality__ReactUpdate.js";

var validators_amount = {
  strategy: /* OnFirstSuccessOrFirstBlur */3,
  validate: (function (param) {
      var amount = param.amount;
      var amountRegex = /^[+]?\d+(\.\d+)?$/;
      if (amount === "") {
        return {
                TAG: 1,
                _0: "Amount is required",
                [Symbol.for("name")]: "Error"
              };
      } else if (amountRegex.test(amount)) {
        return Belt_Option.mapWithDefault(Ethers.Utils.parseEther(amount), {
                    TAG: 1,
                    _0: "Couldn't parse Ether value",
                    [Symbol.for("name")]: "Error"
                  }, (function (etherValue) {
                      return {
                              TAG: 0,
                              _0: etherValue,
                              [Symbol.for("name")]: "Ok"
                            };
                    }));
      } else {
        return {
                TAG: 1,
                _0: "Incorrect number format - please use '.' for floating points.",
                [Symbol.for("name")]: "Error"
              };
      }
    })
};

var validators = {
  isStaking: undefined,
  amount: validators_amount
};

function initialFieldsStatuses(_input) {
  return {
          isStaking: /* Pristine */0,
          amount: /* Pristine */0
        };
}

function initialState(input) {
  return {
          input: input,
          fieldsStatuses: {
            isStaking: /* Pristine */0,
            amount: /* Pristine */0
          },
          collectionsStatuses: undefined,
          formStatus: /* Editing */0,
          submissionStatus: /* NeverSubmitted */0
        };
}

function validateForm(input, validators, fieldsStatuses) {
  var match_0 = {
    TAG: 0,
    _0: input.isStaking,
    [Symbol.for("name")]: "Ok"
  };
  var match = fieldsStatuses.amount;
  var match_0$1 = match ? match._0 : Curry._1(validators.amount.validate, input);
  var isStakingResult = match_0;
  var isStakingResult$1;
  if (isStakingResult.TAG === /* Ok */0) {
    var amountResult = match_0$1;
    if (amountResult.TAG === /* Ok */0) {
      return {
              TAG: 0,
              output: {
                amount: amountResult._0,
                isStaking: isStakingResult._0
              },
              fieldsStatuses: {
                isStaking: {
                  _0: isStakingResult,
                  _1: /* Hidden */1,
                  [Symbol.for("name")]: "Dirty"
                },
                amount: {
                  _0: amountResult,
                  _1: /* Shown */0,
                  [Symbol.for("name")]: "Dirty"
                }
              },
              collectionsStatuses: undefined,
              [Symbol.for("name")]: "Valid"
            };
    }
    isStakingResult$1 = isStakingResult;
  } else {
    isStakingResult$1 = isStakingResult;
  }
  return {
          TAG: 1,
          fieldsStatuses: {
            isStaking: {
              _0: isStakingResult$1,
              _1: /* Hidden */1,
              [Symbol.for("name")]: "Dirty"
            },
            amount: {
              _0: match_0$1,
              _1: /* Shown */0,
              [Symbol.for("name")]: "Dirty"
            }
          },
          collectionsStatuses: undefined,
          [Symbol.for("name")]: "Invalid"
        };
}

function useForm(initialInput, onSubmit) {
  var memoizedInitialState = React.useMemo((function () {
          return initialState(initialInput);
        }), [initialInput]);
  var match = Formality__ReactUpdate.useReducer(memoizedInitialState, (function (state, action) {
          if (typeof action === "number") {
            switch (action) {
              case /* BlurIsStakingField */0 :
                  var result = Formality.validateFieldOnBlurWithoutValidator(state.input.isStaking, state.fieldsStatuses.isStaking, (function (status) {
                          var init = state.fieldsStatuses;
                          return {
                                  isStaking: status,
                                  amount: init.amount
                                };
                        }));
                  if (result !== undefined) {
                    return {
                            TAG: 0,
                            _0: {
                              input: state.input,
                              fieldsStatuses: result,
                              collectionsStatuses: state.collectionsStatuses,
                              formStatus: state.formStatus,
                              submissionStatus: state.submissionStatus
                            },
                            [Symbol.for("name")]: "Update"
                          };
                  } else {
                    return /* NoUpdate */0;
                  }
              case /* BlurAmountField */1 :
                  var result$1 = Formality.validateFieldOnBlurWithValidator(state.input, state.fieldsStatuses.amount, validators_amount, (function (status) {
                          var init = state.fieldsStatuses;
                          return {
                                  isStaking: init.isStaking,
                                  amount: status
                                };
                        }));
                  if (result$1 !== undefined) {
                    return {
                            TAG: 0,
                            _0: {
                              input: state.input,
                              fieldsStatuses: result$1,
                              collectionsStatuses: state.collectionsStatuses,
                              formStatus: state.formStatus,
                              submissionStatus: state.submissionStatus
                            },
                            [Symbol.for("name")]: "Update"
                          };
                  } else {
                    return /* NoUpdate */0;
                  }
              case /* Submit */2 :
                  var match = state.formStatus;
                  if (typeof match !== "number" && match.TAG === /* Submitting */0) {
                    return /* NoUpdate */0;
                  }
                  var match$1 = validateForm(state.input, validators, state.fieldsStatuses);
                  if (match$1.TAG !== /* Valid */0) {
                    return {
                            TAG: 0,
                            _0: {
                              input: state.input,
                              fieldsStatuses: match$1.fieldsStatuses,
                              collectionsStatuses: match$1.collectionsStatuses,
                              formStatus: /* Editing */0,
                              submissionStatus: /* AttemptedToSubmit */1
                            },
                            [Symbol.for("name")]: "Update"
                          };
                  }
                  var output = match$1.output;
                  var error = state.formStatus;
                  var tmp;
                  tmp = typeof error === "number" || error.TAG !== /* SubmissionFailed */1 ? undefined : Caml_option.some(error._0);
                  return {
                          TAG: 1,
                          _0: {
                            input: state.input,
                            fieldsStatuses: match$1.fieldsStatuses,
                            collectionsStatuses: match$1.collectionsStatuses,
                            formStatus: {
                              TAG: 0,
                              _0: tmp,
                              [Symbol.for("name")]: "Submitting"
                            },
                            submissionStatus: /* AttemptedToSubmit */1
                          },
                          _1: (function (param) {
                              var dispatch = param.dispatch;
                              return Curry._2(onSubmit, output, {
                                          notifyOnSuccess: (function (input) {
                                              return Curry._1(dispatch, {
                                                          TAG: 2,
                                                          _0: input,
                                                          [Symbol.for("name")]: "SetSubmittedStatus"
                                                        });
                                            }),
                                          notifyOnFailure: (function (error) {
                                              return Curry._1(dispatch, {
                                                          TAG: 3,
                                                          _0: error,
                                                          [Symbol.for("name")]: "SetSubmissionFailedStatus"
                                                        });
                                            }),
                                          reset: (function (param) {
                                              return Curry._1(dispatch, /* Reset */5);
                                            }),
                                          dismissSubmissionResult: (function (param) {
                                              return Curry._1(dispatch, /* DismissSubmissionResult */4);
                                            })
                                        });
                            }),
                          [Symbol.for("name")]: "UpdateWithSideEffects"
                        };
                  break;
              case /* DismissSubmissionError */3 :
                  var match$2 = state.formStatus;
                  if (typeof match$2 === "number" || match$2.TAG !== /* SubmissionFailed */1) {
                    return /* NoUpdate */0;
                  } else {
                    return {
                            TAG: 0,
                            _0: {
                              input: state.input,
                              fieldsStatuses: state.fieldsStatuses,
                              collectionsStatuses: state.collectionsStatuses,
                              formStatus: /* Editing */0,
                              submissionStatus: state.submissionStatus
                            },
                            [Symbol.for("name")]: "Update"
                          };
                  }
              case /* DismissSubmissionResult */4 :
                  var match$3 = state.formStatus;
                  if (typeof match$3 === "number") {
                    if (match$3 === /* Editing */0) {
                      return /* NoUpdate */0;
                    }
                    
                  } else if (match$3.TAG === /* Submitting */0) {
                    return /* NoUpdate */0;
                  }
                  return {
                          TAG: 0,
                          _0: {
                            input: state.input,
                            fieldsStatuses: state.fieldsStatuses,
                            collectionsStatuses: state.collectionsStatuses,
                            formStatus: /* Editing */0,
                            submissionStatus: state.submissionStatus
                          },
                          [Symbol.for("name")]: "Update"
                        };
              case /* Reset */5 :
                  return {
                          TAG: 0,
                          _0: initialState(initialInput),
                          [Symbol.for("name")]: "Update"
                        };
              
            }
          } else {
            switch (action.TAG | 0) {
              case /* UpdateIsStakingField */0 :
                  var nextInput = Curry._1(action._0, state.input);
                  return {
                          TAG: 0,
                          _0: {
                            input: nextInput,
                            fieldsStatuses: Formality.validateFieldOnChangeWithoutValidator(nextInput.isStaking, (function (status) {
                                    var init = state.fieldsStatuses;
                                    return {
                                            isStaking: status,
                                            amount: init.amount
                                          };
                                  })),
                            collectionsStatuses: state.collectionsStatuses,
                            formStatus: state.formStatus,
                            submissionStatus: state.submissionStatus
                          },
                          [Symbol.for("name")]: "Update"
                        };
              case /* UpdateAmountField */1 :
                  var nextInput$1 = Curry._1(action._0, state.input);
                  return {
                          TAG: 0,
                          _0: {
                            input: nextInput$1,
                            fieldsStatuses: Formality.validateFieldOnChangeWithValidator(nextInput$1, state.fieldsStatuses.amount, state.submissionStatus, validators_amount, (function (status) {
                                    var init = state.fieldsStatuses;
                                    return {
                                            isStaking: init.isStaking,
                                            amount: status
                                          };
                                  })),
                            collectionsStatuses: state.collectionsStatuses,
                            formStatus: state.formStatus,
                            submissionStatus: state.submissionStatus
                          },
                          [Symbol.for("name")]: "Update"
                        };
              case /* SetSubmittedStatus */2 :
                  var input = action._0;
                  if (input !== undefined) {
                    return {
                            TAG: 0,
                            _0: {
                              input: input,
                              fieldsStatuses: {
                                isStaking: /* Pristine */0,
                                amount: /* Pristine */0
                              },
                              collectionsStatuses: state.collectionsStatuses,
                              formStatus: /* Submitted */1,
                              submissionStatus: state.submissionStatus
                            },
                            [Symbol.for("name")]: "Update"
                          };
                  } else {
                    return {
                            TAG: 0,
                            _0: {
                              input: state.input,
                              fieldsStatuses: {
                                isStaking: /* Pristine */0,
                                amount: /* Pristine */0
                              },
                              collectionsStatuses: state.collectionsStatuses,
                              formStatus: /* Submitted */1,
                              submissionStatus: state.submissionStatus
                            },
                            [Symbol.for("name")]: "Update"
                          };
                  }
              case /* SetSubmissionFailedStatus */3 :
                  return {
                          TAG: 0,
                          _0: {
                            input: state.input,
                            fieldsStatuses: state.fieldsStatuses,
                            collectionsStatuses: state.collectionsStatuses,
                            formStatus: {
                              TAG: 1,
                              _0: action._0,
                              [Symbol.for("name")]: "SubmissionFailed"
                            },
                            submissionStatus: state.submissionStatus
                          },
                          [Symbol.for("name")]: "Update"
                        };
              case /* MapSubmissionError */4 :
                  var map = action._0;
                  var error$1 = state.formStatus;
                  if (typeof error$1 === "number") {
                    return /* NoUpdate */0;
                  }
                  if (error$1.TAG !== /* Submitting */0) {
                    return {
                            TAG: 0,
                            _0: {
                              input: state.input,
                              fieldsStatuses: state.fieldsStatuses,
                              collectionsStatuses: state.collectionsStatuses,
                              formStatus: {
                                TAG: 1,
                                _0: Curry._1(map, error$1._0),
                                [Symbol.for("name")]: "SubmissionFailed"
                              },
                              submissionStatus: state.submissionStatus
                            },
                            [Symbol.for("name")]: "Update"
                          };
                  }
                  var error$2 = error$1._0;
                  if (error$2 !== undefined) {
                    return {
                            TAG: 0,
                            _0: {
                              input: state.input,
                              fieldsStatuses: state.fieldsStatuses,
                              collectionsStatuses: state.collectionsStatuses,
                              formStatus: {
                                TAG: 0,
                                _0: Caml_option.some(Curry._1(map, Caml_option.valFromOption(error$2))),
                                [Symbol.for("name")]: "Submitting"
                              },
                              submissionStatus: state.submissionStatus
                            },
                            [Symbol.for("name")]: "Update"
                          };
                  } else {
                    return /* NoUpdate */0;
                  }
              
            }
          }
        }));
  var dispatch = match[1];
  var state = match[0];
  var match$1 = state.formStatus;
  var tmp;
  tmp = typeof match$1 === "number" || match$1.TAG !== /* Submitting */0 ? false : true;
  return {
          updateIsStaking: (function (nextInputFn, nextValue) {
              return Curry._1(dispatch, {
                          TAG: 0,
                          _0: (function (__x) {
                              return Curry._2(nextInputFn, __x, nextValue);
                            }),
                          [Symbol.for("name")]: "UpdateIsStakingField"
                        });
            }),
          updateAmount: (function (nextInputFn, nextValue) {
              return Curry._1(dispatch, {
                          TAG: 1,
                          _0: (function (__x) {
                              return Curry._2(nextInputFn, __x, nextValue);
                            }),
                          [Symbol.for("name")]: "UpdateAmountField"
                        });
            }),
          blurIsStaking: (function (param) {
              return Curry._1(dispatch, /* BlurIsStakingField */0);
            }),
          blurAmount: (function (param) {
              return Curry._1(dispatch, /* BlurAmountField */1);
            }),
          isStakingResult: Formality.exposeFieldResult(state.fieldsStatuses.isStaking),
          amountResult: Formality.exposeFieldResult(state.fieldsStatuses.amount),
          input: state.input,
          status: state.formStatus,
          dirty: (function (param) {
              var match = state.fieldsStatuses;
              if (match.isStaking || match.amount) {
                return true;
              } else {
                return false;
              }
            }),
          valid: (function (param) {
              var match = validateForm(state.input, validators, state.fieldsStatuses);
              if (match.TAG === /* Valid */0) {
                return true;
              } else {
                return false;
              }
            }),
          submitting: tmp,
          submit: (function (param) {
              return Curry._1(dispatch, /* Submit */2);
            }),
          dismissSubmissionError: (function (param) {
              return Curry._1(dispatch, /* DismissSubmissionError */3);
            }),
          dismissSubmissionResult: (function (param) {
              return Curry._1(dispatch, /* DismissSubmissionResult */4);
            }),
          mapSubmissionError: (function (map) {
              return Curry._1(dispatch, {
                          TAG: 4,
                          _0: map,
                          [Symbol.for("name")]: "MapSubmissionError"
                        });
            }),
          reset: (function (param) {
              return Curry._1(dispatch, /* Reset */5);
            })
        };
}

var MintForm = {
  validators: validators,
  initialFieldsStatuses: initialFieldsStatuses,
  initialCollectionsStatuses: undefined,
  initialState: initialState,
  validateForm: validateForm,
  useForm: useForm
};

var initialInput = {
  amount: "",
  isStaking: true
};

function useBalanceAndApproved(erc20Address, spender) {
  var match = ContractHooks.useErc20BalanceRefresh(erc20Address);
  var match$1 = ContractHooks.useERC20ApprovedRefresh(erc20Address, spender);
  return [
          match.data,
          match$1.data
        ];
}

function isGreaterThanApproval(amount, amountApproved) {
  return amount.gt(amountApproved);
}

function isGreaterThanBalance(amount, balance) {
  return amount.gt(balance);
}

function MintForm$SubmitButtonAndTxTracker(Props) {
  var txStateApprove = Props.txStateApprove;
  var txStateMint = Props.txStateMint;
  var resetFormButton = Props.resetFormButton;
  var tokenToMint = Props.tokenToMint;
  var buttonText = Props.buttonText;
  var buttonDisabled = Props.buttonDisabled;
  if (typeof txStateApprove === "number") {
    switch (txStateApprove) {
      case /* UnInitialised */0 :
          break;
      case /* Created */1 :
          return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Please Approve that Float can use your " + Config.paymentTokenName));
      case /* Failed */2 :
          return React.createElement(React.Fragment, undefined, React.createElement("hr", undefined), React.createElement("h1", undefined, "❌ The transaction failed."), React.createElement("p", undefined, React.createElement("a", {
                              href: Config.discordInviteLink,
                              target: "_"
                            }, "This shouldn't happen, please let us help you on discord.")), Curry._1(resetFormButton, undefined));
      
    }
  } else {
    switch (txStateApprove.TAG | 0) {
      case /* SignedAndSubmitted */0 :
          return React.createElement(React.Fragment, undefined, React.createElement("hr", undefined), React.createElement("h1", undefined, React.createElement("a", {
                              href: Config.defaultBlockExplorer + "tx/" + txStateApprove._0,
                              target: "_"
                            }, "Processing Approval ")));
      case /* Declined */1 :
          return React.createElement(React.Fragment, undefined, React.createElement("hr", undefined), React.createElement("h1", undefined, "❌ The transaction was declined by your wallet, you need to accept the transaction to proceed."), React.createElement("p", undefined, "Failure reason: " + txStateApprove._0), Curry._1(resetFormButton, undefined));
      case /* Complete */2 :
          var transactionHash = txStateApprove._0.transactionHash;
          var exit = 0;
          if (typeof txStateMint === "number") {
            switch (txStateMint) {
              case /* UnInitialised */0 :
              case /* Created */1 :
                  exit = 2;
                  break;
              default:
                
            }
          } else if (txStateMint.TAG === /* SignedAndSubmitted */0) {
            return React.createElement(React.Fragment, undefined, React.createElement("hr", undefined), React.createElement("h1", undefined, React.createElement("a", {
                                href: Config.defaultBlockExplorer + "tx/" + transactionHash,
                                target: "_"
                              }, "✅ Approval Complete")), React.createElement("h1", undefined, React.createElement("a", {
                                href: Config.defaultBlockExplorer + "tx/" + txStateMint._0,
                                target: "_"
                              }, "Processing minting " + tokenToMint + " with your " + Config.paymentTokenName)));
          }
          if (exit === 2) {
            return React.createElement(React.Fragment, undefined, React.createElement("hr", undefined), React.createElement("h1", undefined, React.createElement("a", {
                                href: Config.defaultBlockExplorer + "tx/" + transactionHash,
                                target: "_"
                              }, "✅ Approval Complete")), React.createElement("h1", undefined, "Sign the next transaction to mint your"));
          }
          break;
      
    }
  }
  if (typeof txStateMint === "number") {
    switch (txStateMint) {
      case /* UnInitialised */0 :
          return React.createElement(Button.make, {
                      onClick: (function (param) {
                          
                        }),
                      children: buttonText,
                      disabled: buttonDisabled
                    });
      case /* Created */1 :
          return React.createElement(React.Fragment, undefined, React.createElement("hr", undefined), React.createElement("h1", undefined, "Sign the transaction to mint " + tokenToMint + " with your " + Config.paymentTokenName));
      case /* Failed */2 :
          return React.createElement(React.Fragment, undefined, React.createElement("hr", undefined), React.createElement("h1", undefined, "❌ The transaction failed."), React.createElement("p", undefined, React.createElement("a", {
                              href: Config.discordInviteLink,
                              target: "_"
                            }, "This shouldn't happen, please let us help you on discord.")), Curry._1(resetFormButton, undefined));
      
    }
  } else {
    switch (txStateMint.TAG | 0) {
      case /* SignedAndSubmitted */0 :
          return React.createElement(React.Fragment, undefined, React.createElement("hr", undefined), React.createElement("h1", undefined, React.createElement("a", {
                              href: Config.defaultBlockExplorer + "tx/" + txStateMint._0,
                              target: "_"
                            }, "Processing minting " + tokenToMint + " with your " + Config.paymentTokenName + " (click to view)")));
      case /* Declined */1 :
          return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "❌ The transaction was declined by your wallet, you need to accept the transaction to proceed."), React.createElement("p", undefined, "Failure reason: " + txStateMint._0), Curry._1(resetFormButton, undefined));
      case /* Complete */2 :
          return React.createElement(React.Fragment, undefined, React.createElement("hr", undefined), React.createElement("h1", undefined, React.createElement("a", {
                              href: Config.defaultBlockExplorer + "tx/" + txStateMint._0.transactionHash,
                              target: "_"
                            }, "✅ Transaction Complete (click to view)")), Curry._1(resetFormButton, undefined));
      
    }
  }
}

var SubmitButtonAndTxTracker = {
  make: MintForm$SubmitButtonAndTxTracker
};

function MintForm$MintFormInput(Props) {
  var onSubmitOpt = Props.onSubmit;
  var market = Props.market;
  var onChangeSideOpt = Props.onChangeSide;
  var isLong = Props.isLong;
  var onBlurSideOpt = Props.onBlurSide;
  var valueAmountInputOpt = Props.valueAmountInput;
  var optDaiBalanceOpt = Props.optDaiBalance;
  var onBlurAmountOpt = Props.onBlurAmount;
  var onChangeAmountInputOpt = Props.onChangeAmountInput;
  var onMaxClickOpt = Props.onMaxClick;
  var optErrorMessageOpt = Props.optErrorMessage;
  var isStakingOpt = Props.isStaking;
  var disabledOpt = Props.disabled;
  var onBlurIsStakingOpt = Props.onBlurIsStaking;
  var onChangeIsStakingOpt = Props.onChangeIsStaking;
  var txStateApproveOpt = Props.txStateApprove;
  var txStateMintOpt = Props.txStateMint;
  var submitButtonOpt = Props.submitButton;
  var onSubmit = onSubmitOpt !== undefined ? onSubmitOpt : (function (param) {
        
      });
  var onChangeSide = onChangeSideOpt !== undefined ? onChangeSideOpt : (function (param) {
        
      });
  var onBlurSide = onBlurSideOpt !== undefined ? onBlurSideOpt : (function (param) {
        
      });
  var valueAmountInput = valueAmountInputOpt !== undefined ? valueAmountInputOpt : "";
  var optDaiBalance = optDaiBalanceOpt !== undefined ? Caml_option.valFromOption(optDaiBalanceOpt) : undefined;
  var onBlurAmount = onBlurAmountOpt !== undefined ? onBlurAmountOpt : (function (param) {
        
      });
  var onChangeAmountInput = onChangeAmountInputOpt !== undefined ? onChangeAmountInputOpt : (function (param) {
        
      });
  var onMaxClick = onMaxClickOpt !== undefined ? onMaxClickOpt : (function (param) {
        
      });
  var optErrorMessage = optErrorMessageOpt !== undefined ? Caml_option.valFromOption(optErrorMessageOpt) : undefined;
  var isStaking = isStakingOpt !== undefined ? isStakingOpt : true;
  var disabled = disabledOpt !== undefined ? disabledOpt : false;
  var onBlurIsStaking = onBlurIsStakingOpt !== undefined ? onBlurIsStakingOpt : (function (param) {
        
      });
  var onChangeIsStaking = onChangeIsStakingOpt !== undefined ? onChangeIsStakingOpt : (function (param) {
        
      });
  var txStateApprove = txStateApproveOpt !== undefined ? txStateApproveOpt : /* UnInitialised */0;
  var txStateMint = txStateMintOpt !== undefined ? txStateMintOpt : /* UnInitialised */0;
  var submitButton = submitButtonOpt !== undefined ? Caml_option.valFromOption(submitButtonOpt) : React.createElement(Button.make, {
          children: "Login & Mint"
        });
  var formInput = React.createElement(React.Fragment, undefined, React.createElement("div", {
            className: "flex justify-between mb-2"
          }, React.createElement("h2", undefined, market.name + " (" + market.symbol + ")")), React.createElement("select", {
            className: "trade-select",
            disabled: disabled,
            name: "longshort",
            value: isLong ? "long" : "short",
            onBlur: onBlurSide,
            onChange: onChangeSide
          }, React.createElement("option", {
                value: "long"
              }, "Long 🐮"), React.createElement("option", {
                value: "short"
              }, "Short 🐻")), React.createElement(AmountInput.make, {
            placeholder: "Mint",
            value: valueAmountInput,
            optBalance: optDaiBalance,
            disabled: disabled,
            onBlur: onBlurAmount,
            onChange: onChangeAmountInput,
            onMaxClick: onMaxClick
          }), optErrorMessage !== undefined ? React.createElement("div", {
              className: "text-red-500 text-xs"
            }, optErrorMessage) : null, React.createElement("div", {
            className: "flex justify-between items-center"
          }, React.createElement("div", {
                className: "flex items-center"
              }, React.createElement("input", {
                    className: "mr-2",
                    id: "stake-checkbox",
                    checked: isStaking,
                    disabled: disabled,
                    type: "checkbox",
                    onBlur: onBlurIsStaking,
                    onChange: onChangeIsStaking
                  }), React.createElement("label", {
                    className: "text-xs",
                    htmlFor: "stake-checkbox"
                  }, "Stake " + (
                    isLong ? "long" : "short"
                  ) + " tokens")), React.createElement("p", {
                className: "text-xxs hover:text-gray-500"
              }, React.createElement("a", {
                    href: "https://docs.float.capital/docs/stake"
                  }, "Learn more about staking"))));
  var tmp;
  var exit = 0;
  var exit$1 = 0;
  if (typeof txStateApprove === "number") {
    if (txStateApprove === /* Created */1) {
      exit = 1;
    } else {
      exit$1 = 2;
    }
  } else if (txStateApprove.TAG === /* SignedAndSubmitted */0) {
    exit = 1;
  } else {
    exit$1 = 2;
  }
  if (exit$1 === 2) {
    if (typeof txStateMint === "number") {
      if (txStateMint === /* Created */1) {
        exit = 1;
      } else {
        tmp = null;
      }
    } else if (txStateMint.TAG === /* SignedAndSubmitted */0) {
      exit = 1;
    } else {
      tmp = null;
    }
  }
  if (exit === 1) {
    tmp = React.createElement(Loader.Overlay.make, {});
  }
  return React.createElement("div", {
              className: "screen-centered-container"
            }, React.createElement(ViewBox.make, {
                  children: React.createElement(Form.make, {
                        className: "",
                        onSubmit: onSubmit,
                        children: null
                      }, React.createElement("div", {
                            className: "relative"
                          }, formInput, tmp), submitButton)
                }));
}

var MintFormInput = {
  make: MintForm$MintFormInput
};

function MintForm$MintFormSignedIn(Props) {
  var market = Props.market;
  var isLong = Props.isLong;
  var signer = Props.signer;
  var match = ContractActions.useContractFunction(signer);
  var setTxState = match[2];
  var txState = match[1];
  var contractExecutionHandler = match[0];
  var match$1 = ContractActions.useContractFunction(signer);
  var setTxStateApprove = match$1[2];
  var txStateApprove = match$1[1];
  var contractExecutionHandlerApprove = match$1[0];
  var match$2 = React.useState(function () {
        return function (param) {
          
        };
      });
  var setContractActionToCallAfterApproval = match$2[1];
  var contractActionToCallAfterApproval = match$2[0];
  var longShortContractAddress = Config.useLongShortAddress(undefined);
  var daiAddressThatIsTemporarilyHardCoded = Config.useDaiAddress(undefined);
  var match$3 = useBalanceAndApproved(daiAddressThatIsTemporarilyHardCoded, longShortContractAddress);
  var optDaiAmountApproved = match$3[1];
  var optDaiBalance = match$3[0];
  var form = useForm(initialInput, (function (param, _form) {
          var isStaking = param.isStaking;
          var amount = param.amount;
          var mintFunction = function (param) {
            var tmp;
            if (isLong) {
              var arg = market.marketIndex;
              tmp = (function (param) {
                  return param.mintLong(arg, amount);
                });
            } else {
              var arg$1 = market.marketIndex;
              tmp = (function (param) {
                  return param.mintShort(arg$1, amount);
                });
            }
            return Curry._2(contractExecutionHandler, (function (param) {
                          return Contracts.LongShort.make(longShortContractAddress, param);
                        }), tmp);
          };
          var mintAndStakeFunction = function (param) {
            var tmp;
            if (isLong) {
              var arg = market.marketIndex;
              tmp = (function (param) {
                  return param.mintLongAndStake(arg, amount);
                });
            } else {
              var arg$1 = market.marketIndex;
              tmp = (function (param) {
                  return param.mintShortAndStake(arg$1, amount);
                });
            }
            return Curry._2(contractExecutionHandler, (function (param) {
                          return Contracts.LongShort.make(longShortContractAddress, param);
                        }), tmp);
          };
          var needsToApprove = amount.gt(Belt_Option.getWithDefault(optDaiAmountApproved, Ethers$1.BigNumber.from("0")));
          if (needsToApprove) {
            Curry._1(setContractActionToCallAfterApproval, (function (param) {
                    if (isStaking) {
                      return mintAndStakeFunction;
                    } else {
                      return mintFunction;
                    }
                  }));
            var arg = amount.mul(Ethers$1.BigNumber.from("2"));
            return Curry._2(contractExecutionHandlerApprove, (function (param) {
                          return Contracts.Erc20.make(daiAddressThatIsTemporarilyHardCoded, param);
                        }), (function (param) {
                          return param.approve(longShortContractAddress, arg);
                        }));
          } else if (isStaking) {
            return mintAndStakeFunction(undefined);
          } else {
            return mintFunction(undefined);
          }
        }));
  var match$4 = form.amountResult;
  var formAmount = match$4 !== undefined && match$4.TAG === /* Ok */0 ? Caml_option.some(match$4._0) : undefined;
  var resetFormButton = function (param) {
    return React.createElement(Button.make, {
                onClick: (function (param) {
                    Curry._1(form.reset, undefined);
                    Curry._1(setTxStateApprove, (function (param) {
                            return /* UnInitialised */0;
                          }));
                    return Curry._1(setTxState, (function (param) {
                                  return /* UnInitialised */0;
                                }));
                  }),
                children: "Reset & Mint Again"
              });
  };
  var tokenToMint = isLong ? "long " + market.name : "short " + market.name;
  var stakingText = form.input.isStaking ? "Mint & Stake" : "Mint";
  var approveConnector = form.input.isStaking ? "," : " &";
  var position = isLong ? "long" : "short";
  var match$5;
  var exit = 0;
  if (formAmount !== undefined && optDaiBalance !== undefined && optDaiAmountApproved !== undefined) {
    var amount = Caml_option.valFromOption(formAmount);
    var needsToApprove = amount.gt(Caml_option.valFromOption(optDaiAmountApproved));
    var greaterThanBalance = amount.gt(Caml_option.valFromOption(optDaiBalance));
    match$5 = greaterThanBalance ? [
        "Amount is greater than your balance",
        "Insufficient balance",
        true
      ] : [
        undefined,
        needsToApprove ? "Approve" + approveConnector + " " + stakingText + " " + position + " position" : stakingText + " " + position + " position",
        !Curry._1(form.valid, undefined)
      ];
  } else {
    exit = 1;
  }
  if (exit === 1) {
    match$5 = [
      undefined,
      stakingText + " " + position + " position",
      true
    ];
  }
  React.useEffect((function () {
          if (typeof txStateApprove !== "number" && txStateApprove.TAG === /* Complete */2) {
            Curry._1(contractActionToCallAfterApproval, undefined);
            Curry._1(setTxStateApprove, (function (param) {
                    return /* UnInitialised */0;
                  }));
          }
          
        }), [txStateApprove]);
  var router = Router.useRouter();
  return React.createElement(MintForm$MintFormInput, {
              onSubmit: form.submit,
              market: market,
              onChangeSide: (function ($$event) {
                  router.query["mintOption"] = $$event.target.value;
                  return Next.Router.pushObjShallow(router, {
                              pathname: router.pathname,
                              query: router.query
                            });
                }),
              isLong: isLong,
              onBlurSide: (function (param) {
                  return Curry._1(form.blurIsStaking, undefined);
                }),
              valueAmountInput: form.input.amount,
              optDaiBalance: optDaiBalance,
              onBlurAmount: (function (param) {
                  return Curry._1(form.blurAmount, undefined);
                }),
              onChangeAmountInput: (function ($$event) {
                  return Curry._2(form.updateAmount, (function (input, amount) {
                                return {
                                        amount: amount,
                                        isStaking: input.isStaking
                                      };
                              }), $$event.target.value);
                }),
              onMaxClick: (function (param) {
                  return Curry._2(form.updateAmount, (function (input, amount) {
                                return {
                                        amount: amount,
                                        isStaking: input.isStaking
                                      };
                              }), optDaiBalance !== undefined ? Ethers.Utils.formatEther(Caml_option.valFromOption(optDaiBalance)) : "0");
                }),
              optErrorMessage: match$5[0],
              isStaking: form.input.isStaking,
              disabled: form.submitting,
              onBlurIsStaking: (function (param) {
                  return Curry._1(form.blurIsStaking, undefined);
                }),
              onChangeIsStaking: (function ($$event) {
                  return Curry._2(form.updateIsStaking, (function (input, value) {
                                return {
                                        amount: input.amount,
                                        isStaking: value
                                      };
                              }), $$event.target.checked);
                }),
              txStateApprove: txStateApprove,
              txStateMint: txState,
              submitButton: React.createElement(MintForm$SubmitButtonAndTxTracker, {
                    txStateApprove: txStateApprove,
                    txStateMint: txState,
                    resetFormButton: resetFormButton,
                    tokenToMint: tokenToMint,
                    buttonText: match$5[1],
                    buttonDisabled: match$5[2]
                  })
            });
}

var MintFormSignedIn = {
  make: MintForm$MintFormSignedIn
};

function MintForm$1(Props) {
  var market = Props.market;
  var isLong = Props.isLong;
  var router = Router.useRouter();
  var optSigner = ContractActions.useSigner(undefined);
  if (optSigner !== undefined) {
    return React.createElement(MintForm$MintFormSignedIn, {
                market: market,
                isLong: isLong,
                signer: optSigner
              });
  } else {
    return React.createElement("div", {
                onClick: (function (param) {
                    router.push("/login?nextPath=" + router.asPath);
                    
                  })
              }, React.createElement(MintForm$MintFormInput, {
                    market: market,
                    isLong: isLong
                  }));
  }
}

var make = MintForm$1;

export {
  MintForm ,
  initialInput ,
  useBalanceAndApproved ,
  isGreaterThanApproval ,
  isGreaterThanBalance ,
  SubmitButtonAndTxTracker ,
  MintFormInput ,
  MintFormSignedIn ,
  make ,
  
}
/* Form Not a pure module */
