name: Deploy docs to staging

push:
  branches:
    - "*"
    - "!master"

jobs:
  # Source: https://github.community/t/run-job-only-if-folder-changed/118292/2
  has-docs-changes:
    name: Check for changes to docs files
    outputs:
      run_job: ${{ steps.has-docs-changes.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 100 # should be deep enough for our usecase
      - name: check modified files
        id: has-docs-changes
        run: |
          git fetch origin master

          echo "=============== list modified files ==============="
          git diff --name-only origin/master...HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only origin/master...HEAD > files.txt

          while IFS= read -r file
          do
            echo $file
            if [[ $file == docs/* ]]; then
              echo "::set-output name=run_job::true"
              break
            fi
          done < files.txt

  run-deploy-staging:
    name: docs staging deployment
    runs-on: ubuntu-latest
    needs: has-docs-changes
    if: needs.has-docs-changes.outputs.run_job == 'true'

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install node packages
        id: install_node_packages
        run: |
          cd docs && yarn

      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          token: "${{ secrets.API_TOKEN_GITHUB }}"

      - name: run staging ui deploy
        id: run_deploy_staging
        run: |
          cd docs && yarn deploy-to-staging
